name: Github release draft

on:
  push:
    tags:
      - '*'

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest binary artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_and_test.yaml
          branch: master
          name: typedb-loader-latest-binaries
          path: bin

      - name: Create release notes draft
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: TypeDB Loader ${{ github.ref }}
          draft: true
          prerelease: false
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/typedb-loader-${{ github.ref }}.zip
          asset_name: typedb-loader-${{ github.ref }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary tar
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/typedb-loader-${{ github.ref }}.tar.gz
          asset_name: typedb-loader-${{ github.ref }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}